services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080/
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    depends_on:
      - db
    networks:
      - app-network

  db:
    build: ./mongo
    ports:
      - "27110:27017"
    volumes:
      - ./mongo/data:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge